### ISSUE TITLE
Missing attribute in chef 11

### ISSUE THREAD

**Issue by Benjile** [AutomationWithAnsible/ansible-dynamic-inventory-chef#8]
When use against chef 11 this error raises:
`./chef_inventory.py --list
Traceback (most recent call last):
  File "./chef_inventory.py", line 211, in <module>
    main()
  File "./chef_inventory.py", line 207, in main
    ci.execute()
  File "./chef_inventory.py", line 198, in execute
    self.list_nodes()
  File "./chef_inventory.py", line 155, in list_nodes
    if node["automatic"]["roles"] is not None:
KeyError: 'roles'
`

Environment:
ansible 2.0.0.2
chef-server 11.1.5-1
PyChef 0.3.0

**Comment by Benjile** [comment]
Pull request: 
https://github.com/AutomationWithAnsible/ansible-dynamic-inventory-chef/pull/9
